### PR TITLE
Upgrade service framework to support jakarta (JEE 9)

### PR DESCRIPTION
**Pull request by harshit-kumar-v2**
## Description
Please include a summary of the change, motivation and context.

### Testing
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 

### Checklist:
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### Documentation
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.

### CODE REVIEW

**Comment by aaron-steinfeld** [comment]
Change looks fine - I wonder if we should change the artifact name/group?

**Comment by harshit-kumar-v2** [comment]
> Change looks fine - I wonder if we should change the artifact name/group?

I think we can go with new name to go a systematic route.
I suppose we will add new artifact to bom and start consuming in our upgraded services one-by-one?
This will also help us do compatibility changes on services with upgrade SF.

If i am missing something can you also briefly describe how we should move the changes.

**Comment by aaron-steinfeld** [comment]
> I think we can go with new name to go a systematic route.
> I suppose we will add new artifact to bom and start consuming in our upgraded services one-by-one?

I think we're saying the same thing? New, unique artifact so it doesn't conflict with the existing ones. We don't need to maintain the old lineage, we just want to avoid the transitive upgrade.

**Comment by harshit-kumar-v2** [comment]
> > I think we can go with new name to go a systematic route.
> > I suppose we will add new artifact to bom and start consuming in our upgraded services one-by-one?
> 
> I think we're saying the same thing? New, unique artifact so it doesn't conflict with the existing ones. We don't need to maintain the old lineage, we just want to avoid the transitive upgrade.

yeah, just iterating over again to be sure.
i will make this change then.

**Review by kotharironak — DISMISSED** [review]

**Review by kotharironak — APPROVED** [review]

**Pull request merged**
